###
POST http://localhost:3000/register/
Content-Type:application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}


###
GET http://localhost:3000/login/


###
POST http://localhost:3000/login/
Content-Type:application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}


###
GET http://localhost:3000/user/followers/
Authorization:Bearer jwt_token_here
GET http://localhost:3000/user/following/
Authorization:Bearer jwt_token_here

###
POST http://localhost:3000/user/tweets/
Authorization:Bearer jwt_token_here
Content-Type:application/json

{
  "tweet":"The Mornings..."
}


###
DELETE http://localhost:3000/tweets/3/
Authorization:Bearer jwt_token_here

